import SAVEUS from '../assets/SAVEUS.png'
import GNAGS from '../assets/GNAGS.png'
import INFERAL from '../assets/INFERAL.png'
import ZARPAULO from '../assets/ZARPAULO.png'
import BENJAMINHAVFAMILIEN from '../assets/BENJAMINHAV&FAMILIEN.png'
import GALOPDERBY from '../assets/GALOPDERBY.png'
import KAROLINEMOUSING from '../assets/KAROLINEMOUSING.png'
import DOWNTOWNJULY from '../assets/DOWNTOWNJULY.png'
import SPECKTORS from '../assets/SPECKTORS.png'
import BONAD from '../assets/BONAD.png'
import NATURALBORNHIPPIES from '../assets/NATURALBORNHIPPIES.png'
import ELAKELAISET from '../assets/ELAKELAISET.png'
import LARSLILHOLT from '../assets/LARSLILHOLT.png'
import TOSEDRENGETOUR from '../assets/TOSEDRENGETOUR.png'
import RUNERASKHAMPENBERG from '../assets/RUNERASK&HAMPENBERG.png'
import MARIE from '../assets/MARIE.png'
import ANAS from '../assets/ANAS.png'
import SELVG from '../assets/SELVG.png'
import DJ1830 from '../assets/DJ(TBA)18.30.png'
import DJ2015 from '../assets/DJ(TBA)20.15.png'
import DJ2200 from '../assets/DJ(TBA)22.00.png'

const stages = [
  'VIDUNDERBLÅ',
  'DRAGONEN',
  'BYFESTEN',
  'BIRKELUNDEN',
]

const timeLabels = [
  '11:00AM',
  '12:00PM',
  '13:00PM',
  '14:00PM',
  '15:00PM',
  '16:00PM',
  '17:00PM',
  '18:00PM',
  '19:00PM',
  '20:00PM',
  '21:00PM',
  '22:00PM',
  '23:00PM',
  '00:00AM',
  '01:00PM',
]

const lineupData = [
  {
    id: 1,
    name: 'SAVEUS',
    image: SAVEUS,
    cardLeft: 49,
    cardTop: 12,
    cardWidth: 299,
    cardHeight: 92,
    starLeft: 270,
    starTop: 38,
    starSize: 26,
    starOffsetX: 2.5, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 2,
    name: 'GNAGS',
    image: GNAGS,
    cardLeft: 382,
    cardTop: 12,
    cardWidth: 287,
    cardHeight: 92,
    starLeft: 593,
    starTop: 38,
    starSize: 26,
    starOffsetX: 7, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 3,
    name: 'INFERAL',
    image: INFERAL,
    cardLeft: 792,
    cardTop: 12,
    cardWidth: 305,
    cardHeight: 92,
    starLeft: 1007,
    starTop: 38,
    starSize: 26,
    starOffsetX: 9.5, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 4,
    name: 'ZAR PAULO',
    image: ZARPAULO,
    cardLeft: 1218,
    cardTop: 12,
    cardWidth: 338,
    cardHeight: 92,
    starLeft: 1450,
    starTop: 38,
    starSize: 26,
    starOffsetX: 4, 
    starOffsetY: -9.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
    
  },
  {
    id: 5,
    name: 'BENJAMIN HAV & FAMILIEN',
    image: BENJAMINHAVFAMILIEN,
    cardLeft: 1783,
    cardTop: 12,
    cardWidth: 344,
    cardHeight: 92,
    starLeft: 2010,
    starTop: 38,
    starSize: 26,
    starOffsetX: 3, 
    starOffsetY: -9.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },

  {
    id: 6,
    name: 'GALOP-DERBY',
    image: GALOPDERBY,
    cardLeft: 197,
    cardTop: 157,
    cardWidth: 327,
    cardHeight: 92,
    starLeft: 433,
    starTop: 183,
    starSize: 26,
    starOffsetX: 12.5, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 7,
    name: 'KAROLINE MOUSING',
    image: KAROLINEMOUSING,
    cardLeft: 584,
    cardTop: 157,
    cardWidth: 244,
    cardHeight: 92,
    starLeft: 760,
    starTop: 183,
    starSize: 26,
    starOffsetX: 19, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 8,
    name: 'DOWNTOWN JULY',
    image: DOWNTOWNJULY,
    cardLeft: 996,
    cardTop: 157,
    cardWidth: 308,
    cardHeight: 92,
    starLeft: 1226,
    starTop: 183,
    starSize: 26,
    starOffsetX: 15, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 9,
    name: 'SPECKTORS',
    image: SPECKTORS,
    cardLeft: 1437,
    cardTop: 157,
    cardWidth: 279,
    cardHeight: 92,
    starLeft: 1640,
    starTop: 183,
    starSize: 26,
    starOffsetX: 18.5, 
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 10,
    name: 'BONAD',
    image: BONAD,
    cardLeft: 1817,
    cardTop: 157,
    cardWidth: 304,
    cardHeight: 92,
    starLeft: 2036,
    starTop: 183,
    starSize: 26,
    starOffsetX: 14.5, 
    starOffsetY: -9,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },

  {
    id: 11,
    name: 'NATURAL BORN HIPPIES',
    image: NATURALBORNHIPPIES,
    cardLeft: 200,
    cardTop: 302,
    cardWidth: 327,
    cardHeight: 92,
    starLeft: 429,
    starTop: 328,
    starSize: 26,
    starOffsetX: 18.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 12,
    name: 'ELÄKELÄISET',
    image: ELAKELAISET,
    cardLeft: 531,
    cardTop: 302,
    cardWidth: 315,
    cardHeight: 92,
    starLeft: 756,
    starTop: 328,
    starSize: 26,
    starOffsetX: 20,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 13,
    name: 'LARS LILHOLT',
    image: LARSLILHOLT,
    cardLeft: 1034,
    cardTop: 302,
    cardWidth: 300,
    cardHeight: 92,
    starLeft: 1250,
    starTop: 328,
    starSize: 26,
    starOffsetX: 27,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 14,
    name: 'TOSEDRENGE TOUR',
    image: TOSEDRENGETOUR,
    cardLeft: 1518,
    cardTop: 302,
    cardWidth: 311,
    cardHeight: 92,
    starLeft: 1735,
    starTop: 328,
    starSize: 26,
    starOffsetX: 20,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 15,
    name: 'RUNE RASK & HAMPENBERG',
    image: RUNERASKHAMPENBERG,
    cardLeft: 1882,
    cardTop: 302,
    cardWidth: 356,
    cardHeight: 92,
    starLeft: 2146,
    starTop: 328,
    starSize: 26,
    starOffsetX: 15,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },

  {
    id: 16,
    name: 'MARIE',
    image: MARIE,
    cardLeft: 248,
    cardTop: 447,
    cardWidth: 164,
    cardHeight: 92,
    starLeft: 0,
    starTop: 0,
    starSize: 26,
    starOffsetX: 12.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 17,
    name: 'ANAS',
    image: ANAS,
    cardLeft: 444,
    cardTop: 447,
    cardWidth: 163,
    cardHeight: 92,
    starLeft: 0,
    starTop: 0,
    starSize: 26,
    starOffsetX: 13,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 18,
    name: 'SELVG.',
    image: SELVG,
    cardLeft: 621,
    cardTop: 447,
    cardWidth: 193,
    cardHeight: 92,
    starLeft: 760,
    starTop: 473,
    starSize: 26,
    starOffsetX: 20.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 19,
    name: 'DJ (TBA) 18:30',
    image: DJ1830,
    cardLeft: 1050,
    cardTop: 447,
    cardWidth: 256,
    cardHeight: 92,
    starLeft: 1226,
    starTop: 473,
    starSize: 26,
    starOffsetX: 11.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 20,
    name: 'DJ (TBA) 20:15',
    image: DJ2015,
    cardLeft: 1350,
    cardTop: 447,
    cardWidth: 254,
    cardHeight: 92,
    starLeft: 1520,
    starTop: 473,
    starSize: 26,
    starOffsetX: 14.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
  {
    id: 21,
    name: 'DJ (TBA) 22:00',
    image: DJ2200,
    cardLeft: 1704,
    cardTop: 447,
    cardWidth: 313,
    cardHeight: 92,
    starLeft: 1910,
    starTop: 473,
    starSize: 26,
    starOffsetX: 8.5,
    starOffsetY: -8.5,
    myScheduleStarOffsetX: -34.5,
    myScheduleStarOffsetY: -4,
    myScheduleStarSize: 30,
  },
]

export default lineupData
export { stages, timeLabels }